ergo/urls.py
from django.urls import path
from ergo.views import cargaErgo,Lista_ergo,Edita_ergo,Borra_ergo,edit
#aca genero las urls que va a tener la app core de nuestro proyecto 
urlpatterns = [

    #path del core
    path('ergometria/',cargaErgo, name="ergo"),#cargar
    path('listaergometrias/',Lista_ergo, name="listaergo"),#listar
    path('editaergo/<int:pk>/', Edita_ergo.as_view(), name="editaergo"),#editar
    path('editaergo2/<int:pk>/', edit, name="editaergo2"),#editar
    path('borraergo/<int:pk>/', Borra_ergo.as_view(), name="borraergo"),#eliminar CRUD
]

imac2/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views
from antec import views
from ergo import views
from mpi  import views
from usuarios import views
from fventricular import views
from aplicativo import views
from dicom import views



urlpatterns = [
    path('', include('core.urls')),
    path('', include('antec.urls')),
    path('', include('ergo.urls')),
    path('', include('mpi.urls')),
    path('', include('usuarios.urls')),
    path('', include('fventricular.urls')),
    path('', include('aplicativo.urls')),
    path('', include('dicom.urls')),
    path('admin/', admin.site.urls),
]

mpi/urls.py
from django.urls import path
from mpi.views import formpi,Lista_mpi,Edita_mpi,Borra_mpi,edit
#aca genero las urls que va a tener la app core de nuestro proyecto 
urlpatterns = [

    #path del core
    path('prfusionmiocardica/',formpi, name="mpi"),
    path('listampi/',Lista_mpi, name="listampi"),#listar
    path('editampi/<int:pk>/', Edita_mpi.as_view(), name="editampi"),#editar
    path('editampi2/<int:pk>/', edit, name="editampi2"),#editar
    path('borrampi/<int:pk>/', Borra_mpi.as_view(), name="borrampi"),#eliminar CRUD
    
    
]

ergo/models.py
from django.db import models
from core.models import Pacientes,Estudio
# Create your models here.

class Ergometria(models.Model):
    id_ergo=models.AutoField(primary_key=True)
    estudio=models.OneToOneField(Estudio,null=True,on_delete=models.CASCADE)
    paciente_ergo=models.ForeignKey(Pacientes,null=True,on_delete=models.CASCADE)
    ciclo_ergo=models.BooleanField(default=False, blank=True)
    banda_ergo=models.BooleanField(default=False, blank=True)
    carga = models.CharField(max_length=150,verbose_name="Carga",null=True)
    fc_basal = models.IntegerField (verbose_name="Fc basal",null=True)
    tas_basal = models.IntegerField(verbose_name="Tas basal",null=True)
    tad_basal = models.IntegerField(verbose_name="Tad basal",null=True)
    fc_esfuerzo = models.IntegerField(verbose_name="Fc esfuerzo",null=True)
    tas_esfuerzo = models.IntegerField(verbose_name="Tas esfuerzo",null=True)
    tad_esfuerzo = models.IntegerField(verbose_name="Tad esfuerzo",null=True)
    mets = models.IntegerField(verbose_name="Mets",null=True)
    st = models.CharField(max_length=150)
    st_mm = models.CharField(verbose_name="St mm",max_length=50,null=True)
    ta_plana = models.CharField(max_length=150,default=False)
    motivo_suspencion=models.CharField(max_length=150)
    arritmia_sv=models.CharField(max_length=50)
    arritmia_v=models.CharField(max_length=50)
    sintomas=models.CharField(max_length=150)
    fcm_edad = models.IntegerField(verbose_name="Fcm edad",null=True)
    percent_fcmp = models.FloatField(verbose_name="Percent fcmp",null=True)
    itt = models.IntegerField(verbose_name="Itt",null=True)

class Meta: #aplicando un metodo para que pase a español en el admin del framework
        verbose_name= "Ergometria"#aca los paso al español en singular
        verbose_name_plural="Ergometrias"#aca los paso al español en prural
        ordering = ["created"] #con esta funcion puedo ordenar los objetos a medida que los creo

ergo/forms.py
from django import forms
from.models import Ergometria
class FormularioErgometria(forms.ModelForm):
    
    class Meta:
        model = Ergometria
        fields = (
            'paciente_ergo',
            'estudio',
            'ciclo_ergo',
            'banda_ergo',
            'carga',
            'fc_basal', 
            'tas_basal', 
            'tad_basal', 
            'fc_esfuerzo',
            'tas_esfuerzo', 
            'tad_esfuerzo', 
            'mets', 
            'st', 
            'st_mm', 
            'ta_plana', 
            'motivo_suspencion',
            'arritmia_sv',
            'arritmia_v',
            'sintomas',
            'fcm_edad',
            'percent_fcmp', 
            'itt',)


        labels={
            'paciente_ergo':'Paciente',
            'estudio':'estudio',
            'ciclo_ergo':'Cieclo ergo',
            'banda_ergo':'Banda Ergo',
            'carga':'Carga',
            'fc_basal':'Fc basal', 
            'tas_basal':'Tas basal', 
            'tad_basal':'Tad basal', 
            'fc_esfuerzo':'Fc esfuerzo',
            'tas_esfuerzo':'Tas esfuerzo', 
            'tad_esfuerzo':'Tad esfuerzo', 
            'mets':'Mets', 
            'st':'St', 
            'st_mm':'St mm', 
            'ta_plana':'Ta plana', 
            'motivo_suspencion':'Motivo de suspencion',
            'arritmia_sv':'Arritmia sv',
            'arritmia_v':'Arritmia v',
            'sintomas':'Sintomas',
            'fcm_edad':'Edad',
            'percent_fcmp':'Percent fcmp', 
            'itt':'ITT',
        }

        widgets={
            'paciente_ergo':forms.Select(attrs={'class':'form-control','style':'display:none;'}),
            'estudio':forms.Select(attrs={'class':'form-control','style':'display:none;'}),
            'ciclo_ergo':forms.CheckboxInput(attrs={'class':'form-control bordes1' ,'style':'height:30px' ,'id':'CicloErgonometro',  'onchange':'IngresoErgometria(this.value, this.id);'}),
            'banda_ergo':forms.CheckboxInput(attrs={'class':'form-control bordes1' ,'style':'height:30px','id':'bandaDeslizante',  'onchange':'IngresoErgometria(this.value, this.id);' }),
            'carga':forms.TextInput(attrs={'class':'form-control bordes1','id':'icarga','autocomplete':'off', 'onkeyup':'asignarCarga(this.value);' ,'required':'', 'title':'En caso de error seleccionar todo y borrar'}),
            'fc_basal':forms.TextInput(attrs={'class':'form-control bordes1','autocomplete':'off', 'maxlength':'3'}), 
            'tas_basal':forms.TextInput(attrs={'class':'form-control bordes1','autocomplete':'off', 'maxlength':'3'}), 
            'tad_basal':forms.TextInput(attrs={'class':'form-control bordes1','autocomplete':'off', 'maxlength':'3'}), 
            'fc_esfuerzo':forms.TextInput(attrs={'class':'form-control bordes1','id':'ifc_esfuerzo','onchange':'calcular();', 'autocomplete':'off',  'maxlength':'3'}),
            'tas_esfuerzo':forms.TextInput(attrs={'class':'form-control bordes1','id':'itas_esfuerzo','onchange':'calcular();', 'autocomplete':'off', 'maxlength':'3'}), 
            'tad_esfuerzo':forms.TextInput(attrs={'class':'form-control bordes1', 'autocomplete':'off', 'maxlength':'3'}), 
            'mets':forms.TextInput(attrs={'class':'form-control bordes1','autocomplete':'off', 'maxlength':'4'}), 
            'st':forms.TextInput(attrs={'class':'form-control  bordes1'}), 
            'st_mm':forms.TextInput(attrs={'class':'form-control  bordes1'}), 
            'ta_plana':forms.TextInput(attrs={'class':'form-control bordes1'}), 
            'motivo_suspencion':forms.TextInput(attrs={'class':'form-control bordes1'}),
            'arritmia_sv':forms.TextInput(attrs={'class':'form-control bordes1'}),
            'arritmia_v':forms.TextInput(attrs={'class':'form-control bordes1'}),
            'sintomas':forms.TextInput(attrs={'class':'form-control bordes1'}),
            'fcm_edad':forms.TextInput(attrs={'class':'form-control bordes1','id':'ifcm' ,'title':'El calculo de FCM-EDAD se realizara automaticamente.' ,'readonly':'', 'autocomplete':'off'}),
            'percent_fcmp':forms.TextInput(attrs={'class':'form-control bordes1','id':'ifcmp' , 'title':'El calculo de FCPM se realizara automaticamente.' ,'readonly':''}), 
            'itt':forms.TextInput(attrs={'class':'form-control bordes1','id':'iitt' , 'readonly':'', 'title':'El calculo de ITT se realiza automaticamente.' }),
        }

ergo/views.py
from django.shortcuts import render,reverse,redirect,get_object_or_404
from.forms import FormularioErgometria
from core.models import Pacientes,Estudio
from.models import Ergometria
from django.views.generic import ListView,UpdateView,DeleteView
# Create your views here.

def cargaErgo(request):
    if request.method == 'GET':
        q = request.GET.get('q', '')
        eventos = Estudio.objects.filter(pacientes__dni__icontains=q)
        return render(request, 'ergo/ergometria.html', {'eventos': eventos})
    if request.method == 'POST':
        form=FormularioErgometria(request.POST) #indico metodos POST de la transmicion de mis datos
        if form.is_valid():
             #pregunto si mis datos son validos
            form.save(commit=True) #guardo
        return redirect('/prfusionmiocardica/')#al ser esto exitoso redirecciono a home
    else:
        form=FormularioErgometria()#caso contrario atualizo la misma pagina del forulario
        return render(request,'ergo/ergometria.html')#renerizo indicando que exitste formulario
    return render(request,"'ergo/ergometria.html",{'form':form})


def Lista_ergo(request):
    if request.method == 'GET':
        q = request.GET.get('q', '')
        eventos = Ergometria.objects.filter(paciente_ergo__dni__icontains=q)
        return render(request, 'ergo/listaergometria.html', {'eventos': eventos})

class Edita_ergo(UpdateView):
    model=Ergometria
    form_class=FormularioErgometria
    template_name='ergo/editaergo.html'
    def get_success_url(self):
        return reverse('listaergo')
class Borra_ergo(DeleteView):
    model=Ergometria
    template_name='ergo/borraergo.html'
    def get_success_url(self):
        return reverse('listaergo')

def edit(request, pk):
    post = get_object_or_404(Ergometria, pk=pk)
    form=FormularioErgometria(instance=post)
    edad=post.estudio.edad
    if request.method == "POST":
        form = FormularioErgometria(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            
            arg2=int(post.estudio.id_estudio)
            return redirect('aplicativo',arg2)
        else:
            form = FormularioErgometria(instance=post)
    return render(request, "ergo/editaergo2.html", {'form': form,'edad':edad})

ergo/templates/ergo/borraergo.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<style>
    .padre{
      display: flex;
     justify-content: center;
     align-items: center;
  
  }
  
  .bordes1{
  
  border-radius: 10px 10px 10px 10px;
  -moz-border-radius: 10px 10px 10px 10px;
  -webkit-border-radius: 10px 10px 10px 10px;
  border: 0px solid #000000;
  
  }
  </style>
    {% if perms.ergo.delete_ergometria and user.is_authenticated %}
  <form method="post" >
      {% csrf_token %}
     <div class="container mt-md-5 padre">
      <div class="row mt-md-5 ">
      <div class="mt-md-5">
          <div class="mt-md-5">
              <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
                  <h3 class="mt-md-5 mb-md-5" style="color:white;text-align:center;">¿Desea eliminar el estudio del paciente {{object.paciente_ergo}}?</h3>
                  <div class="row padre">
                  <button class="btn btn-danger col-md-4 mb-md-5 mx-5 mb-3" type="submit">Si, eliminar</button>
                  <a class="btn btn-success col-md-4 ml-md-3 mb-md-5 mx-5" href="{% url 'listaergo' %}"> Cancelar</a>
                  </div> 
                  </div>
          </div>
      </div>
      </div>
     </div>
  </form>
  {% else %}
  <div class="container mt-md-5 padre medio">
      <div class="row mt-md-5 ">
      <div class="mt-md-5">
        <div class="mt-md-5">
          <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
            <h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
            <div class="row padre medio">
            <a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
            </div> 
            </div>
        </div>
      </div>
      </div>
       </div>
  {% endif %}
{% endblock content %}

ergo/templates/ergo/editaergo.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<script src="{% static 'ergo/js/funcionesErgometriaEdita.js' %}"></script>

<style>
/* Customize the label (the container) */
.cont {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 22px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* Hide the browser's default checkbox */
.cont input {

  position: absolute;
  opacity: 0;
  cursor: pointer;
  height: 0;
  width: 0;
}

/* Create a custom checkbox */
.checkmark {
	border-radius: 200px 200px 200px 200px;
	-moz-border-radius: 200px 200px 200px 200px;
	-webkit-border-radius: 200px 200px 200px 200px;
  	position: absolute;
  	top: 0;
  	left: 0;
  	height: 22px;
  	width: 22px;
  	background-color: #eee;
}

/* On mouse-over, add a grey background color */
.cont:hover input ~ .checkmark {
  background-color: #ccc;
}

/* When the checkbox is checked, add a blue background */
.cont input:checked ~ .checkmark {
  background-color: #009688	;
}

/* Create the checkmark/indicator (hidden when not checked) */
.checkmark:after {
  content: "";
  position: absolute;
  display: none;
}

/* Show the checkmark when checked */
.cont input:checked ~ .checkmark:after {
  display: block;
}

/* Style the checkmark/indicator */
.cont .checkmark:after {
  left: 9px;
  top: 5px;
  width: 5px;
  height: 10px;
  border: solid white;
  border-width: 0 3px 3px 0;
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
}  
.bordes1{

border-radius: 10px 10px 10px 10px;
-moz-border-radius: 10px 10px 10px 10px;
-webkit-border-radius: 10px 10px 10px 10px;
border: 0px solid #000000;

}
</style>

{% if perms.ergo.view_ergometria and user.is_authenticated %}


<form method="POST">
	{% csrf_token %}
	
<div class="container padre col-md-10 mt-5">
	<div class="card mt-5 col-md-12 bordes1" style="background-color: #263238; ">
				<div class="mt-5 ml-md-5 form-group form-inline " style="display: none;">
					{{form.paciente_ergo}}
					{{form.estudio}}
				</div>
<input type="text" id="edad" value="{{object.estudio.edad}}" style="display: none;">
				<div class="row ml-2 mr-2 mt-3">
				
				
				<div class="col-md-3 mt-5 form-inline">
								
							  
					<label class="cont ">
						{{form.ciclo_ergo}}
						<label class="form-check-label" style="font-size: medium;" for="autoSizingCheck"> CICLO ÉRGONOMETRO(Kgm)</label>
						<span class="checkmark ml-1"></span>
					  </label>	
								
							
				</div>
				

				<div class="form-group col-md-3 mt-3">
						  <label class="control-label " for="inlineFormInput">Carga</label>
						   {{form.carga}}
						  
						   
				</div>
				
				<div class="col-md-3 mt-3 form-group">
				
							<label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">ST</label>
							{{form.st}}

				</div>
				
				<div class="col-md-3 mt-3 form-group"> 
							<label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">ST(mm)</label>
										{{form.st_mm}}
				</div>
						 
				  
				</div> 
			
				<div class="row ml-2 mr-2">
						
				<div class="col-md-3 mt-5 form-inline">
						 
							 <label class="cont ">
								{{form.banda_ergo}}
								<label class="form-check-label " style="font-size: medium;" for="autoSizingCheck"> BANDA DESLIZANTE(%Grad/Km/h)</label>
								<span class="checkmark ml-1"></span>
							  </label>
				</div>
				
				<div class="col-md-3 mt-3 form-group">
						  <label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">METS</label>
						   {{form.mets}}
				
				</div>
		
				<div class="col-md-3 mt-3 form-group">
				
							<label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">TAS BASAL</label>
							{{form.tas_basal}}
				</div>

				
				
				<div class="col-md-3 mt-3 form-group"> 
							<label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">TAS ESFUERZO</label>
										{{form.tas_esfuerzo}}
				</div>
						 
				  
				</div> 
			
				<div class="row ml-2 mr-2">
						
				
					
				  <div class="col-md-3 mt-3 form-group ml-auto">
						  
										<label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">TAD BASAL</label>
										  {{form.tad_basal}}
							  </div>
					<div class="col-md-3 mt-3 form-group">
											<label class="control-label ml-sm-2 mr-sm-2" for="inlineFormInput">TAD ESFUERZO</label>
											{{form.tad_esfuerzo}}
											 
									 </div>
				  
				</div>
			
				<div class="row mr-2 ml-2">
						
				<div class="col-md-3 mt-3 form-group ">
								<label  for="inlineFormCustomSelectPref">FC BASAL</label>
								{{form.fc_basal}}
			
			
						  </div>
				
					 <div class="col-md-3 mt-3 form-group ">
								<label for="inlineFormCustomSelectPref">FC ESFUERZO</label>
								{{form.fc_esfuerzo}}
			  </div>
				<div class="col-md-3 mt-3 form-group ">
								<label for="inlineFormCustomSelectPref">TA PLANA</label>
								 {{form.ta_plana}}
								 </div>
						<div class="col-md-3 mt-3 form-group"> 
							<label class="control-label " for="inlineFormInput">FCM-EDAD:</label>
							{{form.fcm_edad}}
										 </div>
						 
				  
				</div> 
			
				<div class="row mr-2 ml-2">
						
				<div class="col-md-3 mt-3 form-group ">
								<label for="inlineFormCustomSelectPref">MOTIVO DE SUSPENSIÓN</label>
								{{form.motivo_suspencion}}
			
			
						  </div>
				<div class="col-md-3 mt-3 form-group ">
								<label for="inlineFormCustomSelectPref">SÍNTOMAS</label>
								  {{form.sintomas}}
								  </div>
						<div class="col-md-3 mt-3 form-group ml-auto"> 
							<label class="control-label " for="inlineFormInput">%FCPM:</label>
										{{form.percent_fcmp}}
										 </div>
						 
				  
				</div> 
			
				<div class="row mr-2 ml-2">
						
				<div class="col-md-3 mt-3 form-group">
								<label  for="inlineFormCustomSelectPref">ARRITMIA SV</label>
								{{form.arritmia_sv}}
			
			
						  </div>
				
						 <div class="col-md-3 mt-3 form-group">
								<label class=" mr-4" for="inlineFormCustomSelectPref">ARRITMIA V</label>
								{{form.arritmia_v}}
								</div>
			
						<div class="col-md-3 mt-3 form-group ml-auto"> 
							<label class="control-label " for="inlineFormInput">ITT:</label>
							{{form.itt}}
										 </div>
			
				</div> 
			
				<div class="row ml-auto mb-3 mt-3 mr-4"> 
						{% if perms.ergo.change_ergometria and user.is_authenticated %}

								<button type="submit" class="btn btn-success ml-auto bordes1" > Guardar</button>
								{% else %}
								<a href="{% url 'listaergo' %}" class="btn btn-success ml-auto bordes1">Volver</a>
								{% endif %}
						 
				</div>
	</div>
</div>

</form>
{% else %}
<div class="container mt-md-5 padre medio">
		<div class="row mt-md-5 ">
		<div class="mt-md-5">
			<div class="mt-md-5">
				<div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
					<h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
					<div class="row padre medio">
					<a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
					</div> 
					</div>
			</div>
		</div>
		</div>
	   </div>
{% endif %}
 <style>
 	
 	label{
 		color: white;
 	}
	 .padre{
	  display: flex;
	  justify-content: center;
	  align-items: center;

}

 </style>
{% endblock content %}

ergo/templates/ergo/listaergometria.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<style>
  .boton
  {
      width: 200px;
      height: 40px;
      border: none;
      outline: none;
      padding: 0 25px;
      border-radius: 15px 0 0 15px;
  }
  
  .boton2
  {
      position: relative;
      border-radius: 0 15px 15px 0;
      width: 50px;
      height: 40px;
      border: none;
      outline: none;
      cursor: pointer;
      background :#263238;
      color: white;
  }
  .medio{
    justify-content: center;
    display: flex;
  }
  </style>
  {% if perms.ergo.view_ergometria and user.is_authenticated %}
  <div class="container mt-md-5 mb-md-3 col-md-12">
      <div class="row mt-5 d-flex">
          <form class="form-inline" method="GET">
              {% csrf_token %}
               <div class="row mt-sm-2 ml-2 mb-3" >
                  <input type="text" class=" boton ml-md-4 mt-md-5" style="position: relative; border-radius: 15px 0 0 15px; width: 200px; height: 40px;  outline: none; padding: 0 25px; border: solid black 0px" placeholder="Buscar Paciente" name="q"  >
                  <button type="submit" class="boton2 mt-md-5" style=" position: relative; border-radius: 0 15px 15px 0; width: 50px; height: 40px; border: none; outline: none; cursor: pointer; background :#263238; color: white;"><i class="fa fa-search"></i></button>
               </div>
          </form>


      </div>
  </div>
        <table class="table table-dark "id="table" data-toggle="table" data-height="300" >
    <thead style="background-color: #009688;">
      <tr>
          
          <th>Paciente</th>
          <th>DNI</th>
          <th>Fecha de estudio</th>
          <th>Motivo suspensión</th>
          <th>Tad esfuerzo</th>
          <th>Mets</th>
          <th>Editar</th>
          <th>Borrar</th>

      </tr>
    </thead> 


  <tbody>
  {% for pac in eventos  %}
 <tr>
        
          <td>{{pac.paciente_ergo}}</td>
          <td>{{pac.paciente_ergo.dni}}</td>
          <td>{{pac.estudio.fechaAcutal}}</td>
          <td>{{pac.motivo_suspencion}}</td>
          <td>{{pac.tad_esfuerzo}}</td>
          <td>{{pac.mets}}</td>
          {% if perms.ergo.change_ergometria %}
          <td><a class="btn btn-info" href="{% url 'editaergo' pac.id_ergo %}" >Editar</a></td>
          {% else %}
          <td><a class="btn btn-info" href="{% url 'editaergo' pac.id_ergo %}" >Ver</a></td>
          {% endif %}
          {% if perms.ergo.delete_ergometria %}
          <td><a class='btn btn-danger eliminar' href="{% url 'borraergo' pac.id_ergo %}" >Borrar</a></td>
          {% else %}
          {% endif %}
   </tr>
  
  {% endfor %}
     </tbody>
     </table>

     {% else %}
     <div class="container mt-md-5 padre medio">
        <div class="row mt-md-5 ">
        <div class="mt-md-5">
          <div class="mt-md-5">
            <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
              <h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
              <div class="row padre medio">
              <a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
              </div> 
              </div>
          </div>
        </div>
        </div>
         </div>
     {% endif %}
{% endblock content %}