imac2/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views
from antec import views
from ergo import views
from mpi  import views
from usuarios import views
from fventricular import views
from aplicativo import views
from dicom import views



urlpatterns = [
    path('', include('core.urls')),
    path('', include('antec.urls')),
    path('', include('ergo.urls')),
    path('', include('mpi.urls')),
    path('', include('usuarios.urls')),
    path('', include('fventricular.urls')),
    path('', include('aplicativo.urls')),
    path('', include('dicom.urls')),
    path('admin/', admin.site.urls),
]

mpi/urls.py
from django.urls import path
from mpi.views import formpi,Lista_mpi,Edita_mpi,Borra_mpi,edit
#aca genero las urls que va a tener la app core de nuestro proyecto 
urlpatterns = [

    #path del core
    path('prfusionmiocardica/',formpi, name="mpi"),
    path('listampi/',Lista_mpi, name="listampi"),#listar
    path('editampi/<int:pk>/', Edita_mpi.as_view(), name="editampi"),#editar
    path('editampi2/<int:pk>/', edit, name="editampi2"),#editar
    path('borrampi/<int:pk>/', Borra_mpi.as_view(), name="borrampi"),#eliminar CRUD
    
    
]

mpi/models.py
from django.db import models
from core.models import Pacientes,Estudio
# Create your models here.
class Mpi(models.Model):
    id_mpi = models.AutoField(primary_key=True)
    estudio=models.OneToOneField(Estudio,null=True,on_delete=models.CASCADE,blank=True)
    paciente_mpi = models.ForeignKey(Pacientes,null=True, on_delete=models.CASCADE)
    s1_rest = models.IntegerField(null=True)
    s2_rest = models.IntegerField(null=True)
    s3_rest = models.IntegerField(null=True)
    s4_rest = models.IntegerField(null=True)
    s5_rest = models.IntegerField(null=True)
    s6_rest = models.IntegerField(null=True)
    s7_rest = models.IntegerField(null=True)
    s8_rest = models.IntegerField(null=True)
    s9_rest = models.IntegerField(null=True)
    s10_rest = models.IntegerField(null=True)
    s11_rest = models.IntegerField(null=True)
    s12_rest = models.IntegerField(null=True)
    s13_rest = models.IntegerField(null=True)
    s14_rest = models.IntegerField(null=True)
    s15_rest = models.IntegerField(null=True)
    s16_rest = models.IntegerField(null=True)
    s17_rest = models.IntegerField(null=True)
#fin rest
    s1_stress = models.IntegerField(null=True)
    s2_stress = models.IntegerField(null=True)
    s3_stress = models.IntegerField(null=True)
    s4_stress = models.IntegerField(null=True)
    s5_stress = models.IntegerField(null=True)
    s6_stress = models.IntegerField(null=True)
    s7_stress = models.IntegerField(null=True)
    s8_stress = models.IntegerField(null=True)
    s9_stress = models.IntegerField(null=True)
    s10_stress = models.IntegerField(null=True)
    s11_stress = models.IntegerField(null=True)
    s12_stress = models.IntegerField(null=True)
    s13_stress = models.IntegerField(null=True)
    s14_stress = models.IntegerField(null=True)
    s15_stress = models.IntegerField(null=True)
    s16_stress = models.IntegerField(null=True)
    s17_stress = models.IntegerField(null=True)
#fin stress
    s1_dif = models.IntegerField(null=True)
    s2_dif = models.IntegerField(null=True)
    s3_dif = models.IntegerField(null=True)
    s4_dif = models.IntegerField(null=True)
    s5_dif = models.IntegerField(null=True)
    s6_dif = models.IntegerField(null=True)
    s7_dif = models.IntegerField(null=True)
    s8_dif = models.IntegerField(null=True)
    s9_dif = models.IntegerField(null=True)
    s10_dif = models.IntegerField(null=True)
    s11_dif = models.IntegerField(null=True)
    s12_dif = models.IntegerField(null=True)
    s13_dif = models.IntegerField(null=True)
    s14_dif = models.IntegerField(null=True)
    s15_dif = models.IntegerField(null=True)
    s16_dif = models.IntegerField(null=True)
    s17_dif = models.IntegerField(null=True)
#fin dif
    ssr=models.FloatField(null=True)
    sss=models.FloatField(null=True)
    ssd=models.FloatField(null=True)
    cargarchivo=models.FileField(upload_to="misCargas",max_length=150,null=True,blank=True)

mpi/forms.py
from django import forms
from.models import Mpi

class formMpi(forms.ModelForm):
    class Meta:
        model=Mpi

        fields = [

            'paciente_mpi',
            'estudio',
            's1_rest',
            's2_rest',
            's3_rest',
            's4_rest',
            's5_rest',
            's6_rest',
            's7_rest',
            's8_rest',
            's9_rest',
            's10_rest',
            's11_rest',
            's12_rest',
            's13_rest',
            's14_rest',
            's15_rest',
            's16_rest',
            's17_rest',
            's1_stress',
            's2_stress',
            's3_stress',
            's4_stress',
            's5_stress',
            's6_stress',
            's7_stress',
            's8_stress',
            's9_stress',
            's10_stress',
            's11_stress',
            's12_stress',
            's13_stress',
            's14_stress',
            's15_stress',
            's16_stress',
            's17_stress',
            's1_dif',
            's2_dif',
            's3_dif',
            's4_dif',
            's5_dif',
            's6_dif',
            's7_dif',
            's8_dif',
            's9_dif',
            's10_dif',
            's11_dif',
            's12_dif',
            's13_dif',
            's14_dif',
            's15_dif',
            's16_dif',
            's17_dif',
            'ssr',
            'sss',
            'ssd',
            'cargarchivo',
        ]

        labels = {
            'paciente_mpi':'paciente_mpi',
            'estudio':'estudio',
            's1_rest':'s1_rest',
            's2_rest':'s2_rest',
            's3_rest':'s3_rest',
            's4_rest':'s4_rest',
            's5_rest':'s5_rest',
            's6_rest':'s6_rest',
            's7_rest':'s7_rest',
            's8_rest':'s8_rest',
            's9_rest':'s9_rest',
            's10_rest':'s10_rest',
            's11_rest':'s11_rest',
            's12_rest':'s12_rest',
            's13_rest':'s13_rest',
            's14_rest':'s14_rest',
            's15_rest':'s15_rest',
            's16_rest':'s16_rest',
            's17_rest':'s17_rest',
            's1_stress':'s1_stress',
            's2_stress':'s2_stress',
            's3_stress':'s3_stress',
            's4_stress':'s4_stress',
            's5_stress':'s5_stress',
            's6_stress':'s6_stress',
            's7_stress':'s7_stress',
            's8_stress':'s8_stress',
            's9_stress':'s9_stress',
            's10_stress':'s10_stress',
            's11_stress':'s11_stress',
            's12_stress':'s12_stress',
            's13_stress':'s13_stress',
            's14_stress':'s14_stress',
            's15_stress':'s15_stress',
            's16_stress':'s16_stress',
            's17_stress':'s17_stress',
            's1_dif':'s1_dif',
            's2_dif':'s2_dif',
            's3_dif':'s3_dif',
            's4_dif':'s4_dif',
            's5_dif':'s5_dif',
            's6_dif':'s6_dif',
            's7_dif':'s7_dif',
            's8_dif':'s8_dif',
            's9_dif':'s9_dif',
            's10_dif':'s10_dif',
            's11_dif':'s11_dif',
            's12_dif':'s12_dif',
            's13_dif':'s13_dif',
            's14_dif':'s14_dif',
            's15_dif':'s15_dif',
            's16_dif':'s16_dif',
            's17_dif':'s17_dif',
            'ssr':'ssr',
            'sss':'sss',
            'ssd':'ssd',
            'cargarchivo':'cargarchivo',
        }
        widgets = {
            'paciente_mpi':forms.TextInput(attrs={'style':'margin-left: 50px; display:none;'}),
            'estudio':forms.TextInput(attrs={'style':'margin-left: 50px; display:none;'}),
            's1_rest':forms.TextInput(attrs={'id':'issr1','style':'position: absolute; left: 265px; background: transparent;top: 15px;border: 0; outline: none; height: 45px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':'' }),
            's2_rest':forms.TextInput(attrs={'id':'issr2','style':'position: absolute; left: 265px; background: transparent;top: 70px;border: 0; outline: none; height: 45px; width: 60px;text-align: center; font-size: 25px; font-weight:800;' ,'readonly':''}),
            's3_rest':forms.TextInput(attrs={'id':'issr3' ,'style':'position: absolute; left: 112px; background: transparent;top: 122px;  border: 0; outline: none; height: 40px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's4_rest':forms.TextInput(attrs={'id':'issr4'  ,'style':'position: absolute; left: 160px; background: transparent;top: 138px;  border: 0; outline: none; height: 52px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's5_rest':forms.TextInput(attrs={'id':'issr5', 'style':'position: absolute; left: 265px; background: transparent;top: 125px;border: 0; outline: none; height: 40px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's6_rest':forms.TextInput(attrs={'id':'issr6', 'style':'position: absolute; left: 395px; background: transparent;top: 136px;border:0 ; outline: none; height: 50px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's7_rest':forms.TextInput(attrs={'id':'issr7' ,'style':'position: absolute; left: 435px; background: transparent;top: 122px;border: 0; outline: none; height: 40px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's8_rest':forms.TextInput(attrs={'id':'issr8' ,'style':'position: absolute; left: 200px; background: transparent;top: 180px;  border:0 ; outline: none; height: 80px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's9_rest':forms.TextInput(attrs={'id':'issr9' ,'style':'position: absolute; left: 255px; background: transparent;top: 184px;  border: 0; outline: none; height: 80px; width: 80px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's10_rest':forms.TextInput(attrs={'id':'issr10' ,'style':'position: absolute; left: 355px; background: transparent;top: 180px;  border: 0; outline: none; height: 80px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's11_rest':forms.TextInput(attrs={'id':'issr11' , 'style':'position: absolute; left: 112px; background: transparent;top: 280px;  border:0 ; outline: none; height: 40px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's12_rest':forms.TextInput(attrs={' id':'issr12' ,'style':'position: absolute; left: 160px; background: transparent;top: 260px;  border: 0; outline: none; height: 45px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's13_rest':forms.TextInput(attrs={'id':'issr13' ,'style':'position: absolute; left: 265px; background: transparent;top: 285px;  border: 0; outline: none; height: 40px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's14_rest':forms.TextInput(attrs={'id':'issr14' ,'style':'position: absolute; left: 385px; background: transparent;top: 260px;border:0 ; outline: none; height: 45px; width: 36px;text-align: center; font-size: 25px; font-weight:800;' ,'readonly':''}),
            's15_rest':forms.TextInput(attrs={'id':'issr15' ,'style':'position: absolute; left: 435px; background: transparent;top: 280px;border:0 ; outline: none; height: 40px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's16_rest':forms.TextInput(attrs={'id':'issr16' ,'style':'position: absolute; left: 265px; background: transparent;top: 335px;  border: 0; outline: none; height: 40px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's17_rest':forms.TextInput(attrs={'id':'issr17','style':'position: absolute; left: 265px; background: transparent;top: 385px;  border:0 ; outline: none; height: 40px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            
            's1_stress':forms.TextInput(attrs={'id':'isss1' ,'class':'par-i1','style':'position: absolute; left: 420px; background: transparent;top: 15px;border: 0; outline: none; height: 45px; width: 60px;text-align: center; font-size: 25px; font-weight:800;' ,'readonly':''}),
            's2_stress':forms.TextInput(attrs={'id':'isss2' ,'class':'par-i2' ,'style':'position: absolute; left: 420px; background: transparent;top: 70px;border: 0; outline: none; height: 45px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's3_stress':forms.TextInput(attrs={'id':'isss3' ,'class':'par-i3' ,'style':'position: absolute; left: 265px; background: transparent;top: 122px;  border: 0; outline: none; height: 40px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's4_stress':forms.TextInput(attrs={'id':'isss4' ,'class':'par-i4' ,'style':'position: absolute; left: 315px; background: transparent;top: 138px;  border: 0; outline: none; height: 52px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's5_stress':forms.TextInput(attrs={'id':'isss5' ,'class':'par-i5' ,'style':'position: absolute; left: 420px; background: transparent;top: 125px;border: 0; outline: none; height: 40px; width: 60px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),
            's6_stress':forms.TextInput(attrs={'id':'isss6' ,'class':'par-i6' ,'style':'position: absolute; left: 550px; background: transparent;top: 136px;border:0 ; outline: none; height: 50px; width: 36px;text-align: center; font-size: 25px; font-weight:800;','readonly':''}),

mpi/views.py
from django.shortcuts import render,reverse, redirect, get_object_or_404
from .forms import formMpi
from core.models import Pacientes,Estudio
from.models import Mpi
from django.views.generic import ListView,UpdateView,DeleteView

def formpi(request):
    
    if request.method == 'GET':
        q = request.GET.get('q', '')
        eventos = Estudio.objects.filter(pacientes__dni__icontains=q)
        return render(request, 'mpi/imagens.html', {'eventos': eventos})



    if request.method == 'POST':
        form=formMpi(request.POST,request.FILES) #indico metodos POST de la transmicion de mis datos
                                    #se agrega reques.FILES para indicarle que el metodos post va con un archivoS
        if form.is_valid(): #pregunto si mis datos son validos
            form.save() #guardo
        return redirect('/funcionventricular/')#al ser esto exitoso redirecciono a home
    else:
        form=formMpi()#caso contrario atualizo la misma pagina del forulario
    return render(request,"mpi/imagens.html",{'form':form})

def Lista_mpi(request):
    if request.method == 'GET':
        q = request.GET.get('q', '')
        eventos = Mpi.objects.filter(paciente_mpi__dni__icontains=q)
        return render(request, 'mpi/listampi.html', {'eventos': eventos})

class Edita_mpi(UpdateView):
    model=Mpi
    form_class=formMpi
    template_name='mpi/editampi.html'
    def get_success_url(self):
        return reverse('listampi')
class Borra_mpi(DeleteView):
    model=Mpi
    template_name='mpi/borrampi.html'
    def get_success_url(self):
        return reverse('listampi')
        
def edit(request, pk):
    post = get_object_or_404(Mpi, pk=pk)
    form=formMpi(instance=post)
    if request.method == "POST":
        form = formMpi(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            
            arg2=int(post.estudio.id_estudio)
            return redirect('aplicativo',arg2)
        else:
            form = formMpi(instance=post)
    return render(request, "mpi/editampi2.html", {'form': form})



mpi/templates/mpi/borrampi.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}

<style>

.padre{
	display: flex;
   justify-content: center;
   align-items: center;

}

.bordes1{

border-radius: 10px 10px 10px 10px;
-moz-border-radius: 10px 10px 10px 10px;
-webkit-border-radius: 10px 10px 10px 10px;
border: 0px solid #000000;

}
        
        </style>
{% comment %} {% if perms.mpi.delete and user.is_authenticated %} {% endcomment %}
{% if  user.is_authenticated %}

    {% if perms.mpi.delete_mpi  %}

<form method="post" >
        {% csrf_token %}
       <div class="container mt-md-5 padre">
        <div class="row mt-md-5 ">
        <div class="mt-md-5">
            <div class="mt-md-5">
                <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
                    <h3 class="mt-md-5 mb-md-5" style="color:white;text-align:center;">¿Desea eliminar MPI del paciente {{object.paciente_mpi}}?</h3>
                    <div class="row padre">
                    <button class="btn btn-danger col-md-4 mb-md-5 mx-5 mb-3 " type="submit">Si, eliminar</button>
                    <a class="btn btn-success col-md-4 ml-md-3 mb-md-5 mx-5" href="{% url 'listampi' %}"> Cancelar</a>
                    </div> 
                    </div>
            </div>
        </div>
        </div>
       </div>
    </form>

{% else %}

	<div class="container mt-md-5 madre medio">
			<div class="row mt-md-5 ">
			<div class="mt-md-5">
				<div class="mt-md-5">
					<div class="card mt-md-5 col-md-12 bordes1 " style="background-color: #263238; padding: 10px; top: 160px;">
						<h3 class="mt-md-5 mb-md-5" style="color:white; text-align: center;">Este usuario solo tiene permisos para ver estudios de Cámara Gamma</h3>
						<div class="row madre medio botonPermiso">
								<a type="button" href="{% url 'listampi' %}" class="btn ml-auto mr-md-2 mx-2" style="height: 45px; background-color:#009688; color:white; font-family: 'Raleway', sans-serif;
								font-size: large; border-radius: 10px 10px 10px 10px; -moz-border-radius: 10px 10px 10px 10px; -webkit-border-radius: 10px 10px 10px 10px;"  >Lista de Cámara Gamma</a>
						</div> 
						</div>
				</div>
			</div>
			</div>
		   </div>


{% endif %}

    {% else %}
    <div class="container mt-md-5 padre medio">
            <div class="row mt-md-5 ">
            <div class="mt-md-5">
                <div class="mt-md-5">
                    <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
                        <h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
                        <div class="row padre medio">
                        <a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
                        </div> 
                        </div>
                </div>
            </div>
            </div>
           </div>
    {% endif %}

{% endblock content %}

mpi/templates/mpi/listampi.html
{% extends "core/base.html" %}  
{% load static %}
{% block content %}
<style>
@media (max-width: 990px  ) { /* detecta el tamaño de pantalla si es menor a 990px se cambia el nav bar a blanco*/
 
.desplazainputs{
    top: 10px !important;
}
}
    .boton
    {
        width: 200px;
        height: 40px;
        border: none;
        outline: none;
        padding: 0 25px;
        border-radius: 15px 0 0 15px;
    }
    
    .boton2
    {
        position: relative;
        border-radius: 0 15px 15px 0;
        width: 50px;
        height: 40px;
        border: none;
        outline: none;
        cursor: pointer;
        background :#263238;
        color: white;
    }
    .medio{
    justify-content: center;
    display: flex;
  }
    </style>
{% if perms.mpi.view_mpi and user.is_authenticated %}
<body>
    


        <div class="container mt-md-5 mb-md-3 col-md-12">
                <div class="row mt-5 d-flex">
                    <form class="form-inline" method="GET">
                        {% csrf_token %}
                         <div class="row mt-xs-2 ml-2 mb-3" >
                            <input type="text" class=" boton ml-md-4 mt-md-5" style="position: relative; border-radius: 15px 0 0 15px; width: 200px; height: 40px;  outline: none; padding: 0 25px; border: solid black 0px" placeholder="Buscar Paciente" name="q"  >
                            <button type="submit" class="boton2 mt-md-5" style=" position: relative; border-radius: 0 15px 15px 0; width: 50px; height: 40px; border: none; outline: none; cursor: pointer; background :#263238; color: white;"><i class="fa fa-search"></i></button>
                         </div>
                    </form>
        
        
                </div>
            </div>


 <table class="table table-dark table-hover table-striped mb-0 desplazainputs" id="table" data-toggle="table" data-height="300" >
    <thead style="background-color: #009688 ;">
      <tr>
          
          <th>Paciente</th>
          <th>DNI</th>
          <th>Fecha de estudio</th>
          <th>ssr</th>
          <th>sss</th>
          <th>ssd</th>
          <th>Editar</th>
          <th>Borrar</th>

      </tr>
    </thead>
  <tbody>
  {% for pac in eventos  %}
 <tr>
        
          <td>{{pac.paciente_mpi}}</td>
          <th>{{pac.paciente_mpi.dni}}</th>
          <th>{{pac.estudio.fechaAcutal}}</th>
          <td>{{pac.ssr}}</td>
          <td>{{pac.sss}}</td>
          <td>{{pac.ssd}}</td>
          {% if perms.mpi.change_mpi %}
           <td><a class="btn btn-info" href="{% url 'editampi' pac.id_mpi %}" >Editar</a></td>
          {% else %}
           <td><a class="btn btn-info" href="{% url 'editampi' pac.id_mpi %}" >Ver</a></td>
          {% endif %}
          {% if perms.mpi.delete_mpi %}
          <td><a   class='btn btn-danger eliminar' href="{% url 'borrampi' pac.id_mpi %}" >Borrar</a></td>
          {% else %}
          {% endif %}
   </tr>
  
  {% endfor %}
     </tbody>
     </table>
     {% else %}
     <div class="container mt-md-5 padre medio">
            <div class="row mt-md-5 ">
            <div class="mt-md-5">
                <div class="mt-md-5">
                    <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
                        <h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
                        <div class="row padre medio">
                        <a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
                        </div> 
                        </div>
                </div>
            </div>
            </div>
           </div>
        </body>
{% endif %}
{% endblock content %}