antec/urls.py
from django.urls import path
from antec.views import form_antecedente,Lista_antecedentes,Edita_antecedentes,Borra_antecedente,edit
#aca genero las urls que va a tener la app core de nuestro proyecto 
urlpatterns = [

    #path del core
    path('antecedente/',form_antecedente, name="antecedentes"),
    path('listaantecedente/',Lista_antecedentes, name="listaantecedentes"),
    path('editaantecedente/<int:pk>/', Edita_antecedentes.as_view(), name="editaantec"),
    path('editaantec/<int:pk>/', edit, name="editaantec2"),
    path('borrarantecedente/<int:pk>/', Borra_antecedente.as_view(), name="borraantec"),
    #path('busqueda/', views.busqueda, name="busquedas"),
    
    
]

imac2/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views
from antec import views
from ergo import views
from mpi  import views
from usuarios import views
from fventricular import views
from aplicativo import views
from dicom import views



urlpatterns = [
    path('', include('core.urls')),
    path('', include('antec.urls')),
    path('', include('ergo.urls')),
    path('', include('mpi.urls')),
    path('', include('usuarios.urls')),
    path('', include('fventricular.urls')),
    path('', include('aplicativo.urls')),
    path('', include('dicom.urls')),
    path('admin/', admin.site.urls),
]

mpi/urls.py
from django.urls import path
from mpi.views import formpi,Lista_mpi,Edita_mpi,Borra_mpi,edit
#aca genero las urls que va a tener la app core de nuestro proyecto 
urlpatterns = [

    #path del core
    path('prfusionmiocardica/',formpi, name="mpi"),
    path('listampi/',Lista_mpi, name="listampi"),#listar
    path('editampi/<int:pk>/', Edita_mpi.as_view(), name="editampi"),#editar
    path('editampi2/<int:pk>/', edit, name="editampi2"),#editar
    path('borrampi/<int:pk>/', Borra_mpi.as_view(), name="borrampi"),#eliminar CRUD
    
    
]

antec/models.py
from django.db import models
from core.models import Pacientes,Estudio

# Create your models here.

class Antecedentes(models.Model):
    id_antecedentes=models.AutoField(primary_key=True)
    estudio=models.OneToOneField(Estudio,null=True,on_delete=models.CASCADE)
    paciente_antecedente=models.OneToOneField(Pacientes,on_delete=models.CASCADE,null=True)
    fcrv_hta = models.BooleanField(default=False, null=True )
    fcrv_dta = models.BooleanField(default=False, null=True )
    fecha_fcrv_hta = models.DateField(null = True, blank=True)
    fecha_fcrv_dta = models.DateField(null = True, blank=True)
    anteced_fliar = models.BooleanField(default=False, null=True)
    dislipemia = models.BooleanField(default=False, null=True)
    estres = models.BooleanField(default=False, null=True)
    tabaquismo = models.BooleanField(default=False, null=True )
    ex_tabaquismo = models.BooleanField(default=False, null=True )
    sedentarismo = models.BooleanField(default=False, null=True)
    chagas = models.BooleanField(default=False, null=True)
    marcapasos = models.BooleanField(default=False, null=True)
    resincron = models.BooleanField(default=False, null=True)
    cdi = models.BooleanField(default=False, null=True )
    crm_hta = models.BooleanField(default=False, null=True)
    fecha_crm_hta = models.DateTimeField(null = True, blank=True)
    pm = models.BooleanField(default=False, null=True)
    pm_da = models.BooleanField(default=False, null=True)
    pm_dg = models.BooleanField(default=False, null=True)
    pm_cx = models.BooleanField(default=False, null=True)
    pr = models.BooleanField(default=False, null=True)
    pr_dg = models.BooleanField(default=False, null=True)
    pr_cx = models.BooleanField(default=False, null=True)
    pv = models.BooleanField(default=False, null=True)
    pv_da = models.BooleanField(default=False, null=True)
    pv_dg = models.BooleanField(default=False, null=True)
    pv_cx = models.BooleanField(default=False, null=True)
    infarto = models.BooleanField(default=False, null=True)
    fecha_infarto_reciente = models.DateField(null = True, blank=True)
    atc1 = models.BooleanField(default=False, null=True)
    atc1_da = models.BooleanField(default=False, null=True)
    atc1_dg = models.BooleanField(default=False, null=True)
    atc1_cx = models.BooleanField(default=False, null=True)
    atc1_cd = models.BooleanField(default=False, null=True)
    atc1_stent_bms = models.BooleanField(default=False, null=True)
    atc1_stent_des = models.BooleanField(default=False, null=True)
    atc2 = models.BooleanField(default=False, null=True)
    atc2_da = models.BooleanField(default=False, null=True)
    atc2_dg = models.BooleanField(default=False, null=True)
    atc2_cx = models.BooleanField(default=False, null=True)
    atc2_cd = models.BooleanField(default=False, null=True)
    atc2_stent_bms = models.BooleanField(default=False, null=True)
    atc2_stent_des = models.BooleanField(default=False, null=True)
    atc3 = models.BooleanField(default=False, null=True)
    atc3_da = models.BooleanField(default=False, null=True)
    atc3_dg = models.BooleanField(default=False, null=True)
    atc3_cx = models.BooleanField(default=False, null=True)
    atc3_cd = models.BooleanField(default=False, null=True)
    atc3_stent_bms = models.BooleanField(default=False, null=True)
    atc3_stent_des = models.BooleanField(default=False, null=True)
    otros_antecedentes = models.TextField(null = True, blank=True)

class Meta: #aplicando un metodo para que pase a español en el admin del framework
        verbose_name= "Antecedente"#aca los paso al español en singular
        verbose_name_plural="Antecedentes"#aca los paso al español en prural
        ordering = ["created"] #con esta funcion puedo ordenar los objetos a medida que los creo
    

antec/forms.py
from django import forms
from.models import Antecedentes

class formAntecedentes(forms.ModelForm):
        
        class Meta:
            model=Antecedentes

            fields = [
                'paciente_antecedente',
                'estudio',
                'fcrv_hta' ,
                'fcrv_dta' ,
                'fecha_fcrv_hta' ,
                'fecha_fcrv_dta',
                'anteced_fliar',
                'dislipemia' ,
                'estres' ,
                'tabaquismo' ,
                'ex_tabaquismo',
                'sedentarismo' ,
                'chagas' ,
                'marcapasos' ,
                'resincron' ,
                'cdi' ,
                'crm_hta' ,
                'fecha_crm_hta',
                'pm' ,
                'pm_da' ,
                'pm_dg' ,
                'pm_cx' ,
                'pr' ,
                'pr_dg' ,
                'pr_cx' ,
                'pv',
                'pv_da' ,
                'pv_dg' ,
                'pv_cx' ,
                'infarto' ,
                'fecha_infarto_reciente' ,
                'atc1' ,
                'atc1_da' ,
                'atc1_dg' ,
                'atc1_cx' ,
                'atc1_cd' ,
                'atc1_stent_bms' ,
                'atc1_stent_des' ,
                'atc2' ,
                'atc2_da' ,
                'atc2_dg' ,
                'atc2_cx' ,
                'atc2_cd' ,
                'atc2_stent_bms' ,
                'atc2_stent_des' ,
                'atc3' ,
                'atc3_da' ,
                'atc3_dg' ,
                'atc3_cx' ,
                'atc3_cd' ,
                'atc3_stent_bms' ,
                'atc3_stent_des' ,
                'otros_antecedentes' ,
            ]

            labels = {
                #grupo-FCRV
                'paciente_antecedente':'Paciente',
                'estudio':'estudio',
                'fcrv_hta' : 'HTA',
                'fcrv_dta' :'DTA',
                'fecha_fcrv_hta' :'Fecha HTA',
                'fecha_fcrv_dta':'Fecha DTA',
                'anteced_fliar':'Antecedente familiar',
                'dislipemia' :'Displemia',
                'estres':'Estres' ,
                'tabaquismo':'TABAQUISMO' ,
                'ex_tabaquismo':'Ex tabaquismo',
                'sedentarismo':'Sedentarismo',
                'chagas':'Chagas' ,
                'marcapasos':'Marcapasos' ,
                'resincron':'Resincron' ,
                'cdi':'Cdi' ,
                #grupo-crm
                'crm_hta' :' HTA',
                'fecha_crm_hta':'Fecha crm hta',
                'pm' :'Pm',
                'pm_da':'DA' ,
                'pm_dg' :'DG',
                'pm_cx':'CX' ,
                'pr':'Pr' ,
                'pr_dg':'Pr dg' ,
                'pr_cx':'Pr cx' ,
                'pv':'Pv',
                'pv_da':'Pv da' ,
                'pv_dg' :'Pv dg',
                'pv_cx':'Pv cx' ,
                'infarto':'Infarto' ,
                'fecha_infarto_reciente':'Fecha de infarto reciente' ,
                'atc1':'Atc 1' ,
                'atc1_da':'Atc 1 da' ,
                'atc1_dg' :'Atc 1 dg',
                'atc1_cx': 'Atc 1 cx' ,
                'atc1_cd':'Atc 1 cd' ,
                'atc1_stent_bms':'Atc 1 sent bms' ,
                'atc1_stent_des':'Atc 1 sent des' ,
                'atc2' :'Atc 2',
                'atc2_da':'Atc 2 da' ,
                'atc2_dg':'Atc 2 dg' ,
                'atc2_cx':'Atc 2 cx' ,
                'atc2_cd':'Atc 2 cd' ,
                'atc2_stent_bms':'Atc 2 sen bms' ,
                'atc2_stent_des':'Atc 2 sen des' ,
                'atc3':'Atc 3' ,
                'atc3_da':'Atc 3 da',
                'atc3_dg':'Atc 3 dg' ,
                'atc3_cx' :'Atc 3 cx',
                'atc3_cd' :'Atc 3 cd',
                'atc3_stent_bms':'Atc 3 sent bms' ,
                'atc3_stent_des':'Atc 3 sent des',
                'otros_antecedentes':'Otros antecedentes' ,

            }

            widgets = {
                'paciente_antecedente':forms.Select(attrs={'class':'form-control' }),
                'estudio':forms.Select(attrs={'class':'form-control' }),
                'fcrv_hta' :forms.CheckboxInput(attrs={'class':'form-control', }),
                'fcrv_dta' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'fecha_fcrv_hta':forms.DateInput(attrs={'class':'form-control bordes col-md-12','id':'fecha_fcrv_hta',  'onchange':'calcularAños(this.id);' }),
                'fecha_fcrv_dta':forms.DateInput(attrs={'class':'form-control bordes col-md-12','id':'fecha_fcrv_dta',  'onchange':'calcularAños(this.id);' }),
                'anteced_fliar':forms.CheckboxInput(attrs={'class':'form-control'}),
                'dislipemia' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'estres':forms.CheckboxInput(attrs={'class':'form-control' }), 
                'tabaquismo':forms.CheckboxInput(attrs={'class':'form-control','id':'tabaquismo', 'onchange':'unicaOpcion(this.id)' }), 
                'ex_tabaquismo':forms.CheckboxInput(attrs={'class':'form-control','id':'ex_tabaquismo', 'onchange':'unicaOpcion(this.id)'}),
                'sedentarismo':forms.CheckboxInput(attrs={'class':'form-control'}),
                'chagas' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'marcapasos' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'resincron' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'cdi' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'crm_hta':forms.CheckboxInput(attrs={'class':'form-control' }) ,
                'fecha_crm_hta':forms.DateInput(attrs={'class':'form-control ml-5 bordes col-md-7','id':'fecha_crm_hta',  'onchange':'calcularAños(this.id);' }),
                'pm' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pm_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pm_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pm_cx' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'pr' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pr_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pr_cx':forms.CheckboxInput(attrs={'class':'form-control ml-3' }) ,
                'pv':forms.CheckboxInput(attrs={'class':'form-control' }),
                'pv_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pv_dg' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'pv_cx' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'infarto' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'fecha_infarto_reciente':forms.DateInput(attrs={'class':'form-control ml-md-3 bordes','id':'fecha_infarto_reciente',  'onchange':'calcularAños(this.id);' }) ,
                'atc1':forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc1_da':forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_dg' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_cx' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_cd' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_stent_bms' :forms.CheckboxInput(attrs={'class':'form-control ml-4'}),
                'atc1_stent_des' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'atc2' :forms.CheckboxInput(attrs={'class':'form-control' ,}),
                'atc2_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_cx' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_cd' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_stent_bms' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_stent_des' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_cx' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_cd' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_stent_bms' :forms.CheckboxInput(attrs={'class':'form-control' ,}),
                'atc3_stent_des' :forms.CheckboxInput(attrs={'class':'form-control' ,}),
                'otros_antecedentes' :forms.Textarea(attrs={'class':'form-control col-md-11 ml-4',  'rows' : '8' }),
            }

antec/views.py
from django.shortcuts import render,reverse, redirect, get_object_or_404
from.forms import formAntecedentes
from django.db.models import Q
from core.models import Estudio
from.models import Antecedentes
from django.views.generic import ListView,UpdateView,DeleteView
# Create your views here.
def form_antecedente(request):
    if request.method == 'GET':
        q = request.GET.get('q', '')
        eventos = Estudio.objects.filter(pacientes__dni__icontains=q)
        return render(request, 'antec/antecedentes.html', {'eventos': eventos})
    if request.method == 'POST':
        form=formAntecedentes(request.POST) #indico metodos POST de la transmicion de mis datos
        if form.is_valid():
             #pregunto si mis datos son validos
            form.save(commit=True) #guardo
        return redirect('/ergometria/')#al ser esto exitoso redirecciono a home
    else:
        form=formAntecedentes#caso contrario atualizo la misma pagina del forulario
        return render(request,'antec/antecedentes.html')#renerizo indicando que exitste formulario
    return render(request,"antec/antecedentes.html",{'form':form})

def Lista_antecedentes(request):
    if request.method == 'GET':
        q = request.GET.get('q', '')
        eventos = Antecedentes.objects.filter(paciente_antecedente__dni__icontains=q)
        return render(request, 'antec/listaantecedentes.html', {'eventos': eventos})

class Edita_antecedentes(UpdateView):
    model=Antecedentes
    form_class=formAntecedentes
    template_name='antec/editaantecedentes.html'
    def get_success_url(self):
        return reverse('listaantecedentes')

class Borra_antecedente(DeleteView):
    model=Antecedentes
    template_name='antec/borraantecedentes.html'
    def get_success_url(self):
        return reverse('listaantecedentes')

def edit(request, pk):
    post = get_object_or_404(Antecedentes, pk=pk)
    form=formAntecedentes(instance=post)
    if request.method == "POST":
        form = formAntecedentes(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            
            arg2=int(post.estudio.id_estudio)
            return redirect('aplicativo',arg2)
        else:
            form = formAntecedentes(instance=post)
    return render(request, "antec/editaantecedentes2.html", {'form': form})

antec/templates/antec/borraantecedentes.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<style>
        .padre{
          display: flex;
         justify-content: center;
         align-items: center;
      
      }
      
      .bordes1{
      
      border-radius: 10px 10px 10px 10px;
      -moz-border-radius: 10px 10px 10px 10px;
      -webkit-border-radius: 10px 10px 10px 10px;
      border: 0px solid #000000;
      
      }
</style>
{% if perms.antec.delete_antecedentes and user.is_authenticated %}
<form method="post" >
            {% csrf_token %}
           <div class="container mt-md-5 padre">
            <div class="row mt-md-5 ">
            <div class="mt-md-5">
                <div class="mt-md-5">
                    <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
                        <h3 class="mt-md-5 mb-md-5" style="color:white; text-align:center;">¿Desea eliminar el estudio del paciente {{object.paciente_antecedente}}?</h3>
                        <div class="row padre">
                        <button class="btn btn-danger col-md-4 mb-md-5 mx-5 mb-3" type="submit">Si, eliminar</button>
                        <a class="btn btn-success col-md-4 ml-md-3 mb-md-5 mx-5" href="{% url 'listaantecedentes' %}"> Cancelar</a>
                        </div> 
                        </div>
                </div>
            </div>
            </div>
           </div>
</form>
{% else %}
<div class="container mt-md-5 padre medio">
        <div class="row mt-md-5 ">
        <div class="mt-md-5">
            <div class="mt-md-5">
                <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
                    <h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
                    <div class="row padre medio">
                    <a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
                    </div> 
                    </div>
            </div>
        </div>
        </div>
       </div>
{% endif %}
{% endblock content %}

antec/templates/antec/busqueda.html
<html>
<head>
        {%block title%} <title>Listado de Antecedentes Patologicos</title>{%endblock%}
</head>
<body>
<h1> Buscar el paciente</h1>
<form action="{% url 'busquedas' %}" method="GET">
{% csrf_token %}
    <input name="q" placeholder="Escribe el nombre de una ciudad" id="buscador">
    <button class="btn btn-primary mr-sm-4 my-2 ml-md-3" type="submit">Guardar</button>
</form>
{% if eventos %}
    {% for k in eventos %}
        <table border="0px" width="300px">
        <tr>
        <td>nombre</td>
        <td>{{k.nombre}}</td>
        </tr>
        <tr>
        <td>apellido</td>
        <td>{{k.apellido}}</td>
        </tr>
        <tr>
        <td>dni</td>
        <td>{{k.dni}}</td>
        </tr>
         <tr>
        <td>ID</td>
        <td>{{k.id_pac}}</td>
        </tr>
    {% endfor %}

{% else %}
{% endif %}


</body>
</html>

antec/templates/antec/listaantecedentes.html
{% extends "core/base.html" %}
{%block title%} <title>Lista Antecedentes Patologicos</title>{%endblock%}
{% load static %}
{% block content %}
<style>
.medio{
    justify-content: center;
    display: flex;
  }
    .boton
    {
        width: 200px;
        height: 40px;
        border: none;
        outline: none;
        padding: 0 25px;
        border-radius: 15px 0 0 15px;
    }
    
    .boton2
    {
        position: relative;
        border-radius: 0 15px 15px 0;
        width: 50px;
        height: 40px;
        border: none;
        outline: none;
        cursor: pointer;
        background :#263238;
        color: white;
    }
    
    </style> {% if user.is_authenticated and perms.antec.view_antecedentes %}
     <div class="container mt-md-5 mb-md-3 col-md-12">
        <div class="row mt-5 d-flex">
            <form class="form-inline" method="GET">
                {% csrf_token %}
                 <div class="row mt-sm-2 ml-2 mb-3" >
                    <input type="text" class=" boton ml-md-4 mt-md-5" style="position: relative; border-radius: 15px 0 0 15px; width: 200px; height: 40px;  outline: none; padding: 0 25px; border: solid black 0px" placeholder="Buscar Paciente" name="q"  >
                    <button type="submit" class="boton2 mt-md-5" style=" position: relative; border-radius: 0 15px 15px 0; width: 50px; height: 40px; border: none; outline: none; cursor: pointer; background :#263238; color: white;"><i class="fa fa-search"></i></button>
                 </div>
            </form>
  
  
        </div>
    </div>
        <br>
        <table class="table table-dark" id="table" data-toggle="table" data-height="300">
    <thead style="background-color: #009688;">
      <tr>
          
          <th>Paciente</th>
          <th>DNI</th>
          <th>Fecha de estudio</th>
          <th>fecha fcrv dta</th>
          <th>otros antecedentes medica</th>
          <th>Editar</th>
          <th>Borrar</th>

      </tr>
    </thead>
  

   
  <tbody>
 
  {% for pac in eventos  %}
 <tr>
        
          <td>{{pac.paciente_antecedente}}</td>
          <td>{{pac.paciente_antecedente.dni}}</td>
          <td>{{pac.estudio.fechaAcutal}}</td>
          {% if pac.fecha_fcrv_dta == none %}
          <td>No</td>
          {% else %}
          <td>{{pac.fecha_fcrv_dta}}</td>
          {% endif %}
          <td>{{pac.otros_antecedentes}}</td>
          {% if perms.antec.change_antecedentes %}
          <td><a class="btn btn-info" href="{% url 'editaantec' pac.id_antecedentes %}" >Editar</a></td>
          {% else %}
          <td><a class="btn btn-info" href="{% url 'editaantec' pac.id_antecedentes %}" >Ver</a></td>
          {% endif %}
         {% if perms.antec.delete_antecedentes %}
         <td><a   class='btn btn-danger eliminar' href="{% url 'borraantec' pac.id_antecedentes %}" >Borrar</a></td>  
         {% else %}
         {% endif %}
   </tr>
  
  {% endfor %}
     </tbody>
     </table>
     {% else %}
     <div class="container mt-md-5 padre medio">
        <div class="row mt-md-5 ">
        <div class="mt-md-5">
          <div class="mt-md-5">
            <div class="card mt-md-5 col-md-12 bordes1" style="background-color: #263238; padding: 10px; top: 160px;">
              <h3 class="mt-md-5 mb-md-5" style="color:white;">Este usuario no está autenticado</h3>
              <div class="row padre medio">
              <a class="btn btn-success col-md-4 ml-md-3 mb-md-5" href=" /logout ">Login </a>
              </div> 
              </div>
          </div>
        </div>
        </div>
         </div>
    {% endif %}

{% endblock content %}